apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculator-service
  template:
    metadata:
      labels:
        app: calculator-service
    spec:
      containers:
      - name: calculator-service
        image: davidchen98/calculator
        ports:
        - containerPort: 8081
