apiVersion: v1
kind: Service
metadata:
  name: calculator
  labels:
    app: calculator
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: calculator
  type: ClusterIP
