apiVersion: v1
kind: Service
metadata:
  name: calculator-service
  labels:
    app: calculator-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: calculator-service
  type: ClusterIP
