apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-service
  template:
    metadata:
      labels:
        app: storage-service
    spec:
      containers:
      - name: storage-service
        image: davidchen98/storage
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
          - name: DB_HOST
            value: mysql
          - name: CALCULATOR_HOST
            value: calculator-service
