apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
      - name: storage
        image: davidchen98/storage
        ports:
        - containerPort: 8080
        env:
          - name: DB_HOST
            value: mysql
          - name: CALCULATOR_HOST
            value: calculator
