apiVersion: v1
kind: Service
metadata:
  name: storage-service
  labels:
    app: storage-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 8080
      protocol: TCP
      nodePort: 31002
  selector:
    app: storage-service
