apiVersion: v1
kind: Service
metadata:
  name: storage-lb
  labels:
    app: storage
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 31001
  selector:
    app: storage
